### ISSUE TITLE
[1.16.2] Techemistry 1.16.2 needs ALib

### ISSUE THREAD

**Issue by realTIMematrix** [al132mc/techemistry#11]
Hi,

if you load techemistry techemistry-1.16.2-1.jar in curseforge it loads the wrong alib, but i can't see any alib for 1.16.2.
Could you please fix this? game does not start and crashes

best regards

**Comment by ghost** [comment]
Right sorry, I forgot to upload it.

**Comment by ghost** [comment]
It's up and approved now - [here](https://www.curseforge.com/minecraft/mc-mods/a-lib/files/3046572)

Thanks for bringing this to my attention
