### ISSUE TITLE
Strange Bug with Mekanism.

### ISSUE THREAD

**Issue by ultranine** [al132mc/techemistry#13]
Earlier today I was trying to make a modpack on 1.16.3, using the most recent version of ALib, ChemLib, Techemistry, and Alchemistry, as well as the latest version of Mekanism, compiled from GitHub. However, upon opening a machine from Techemistry, the background for the GUI was missing, with only the text for the machine showing, as well as a white box where the icons usually were. The machine was still completely useable, however, finding the slots to place items in was nearly impossible. I'm 99% sure Mekanism triggered this, as there weren't any issues beforehand. Can you fix this issue, if possible?

**Comment by ghost** [comment]
I actually suspect this was caused by the update to ALib today. I will take a look within the next day hopefully

**Comment by ghost** [comment]
Okay, a fix should be up now v1.16.3-3. Thank you for bringing this to my attention.
