### ISSUE TITLE
[1.16.3] Exception on Join

### ISSUE THREAD

**Issue by TheRealM18** [al132mc/techemistry#14]
When trying to make a multiplayer server, it will launch, both on the client, and server, but you can not network them together.  This only happens on Techemistry not the other mod of yours.  If you could fix this asap that would be greatly appreciated.

**Comment by ghost** [comment]
Could you give me more information please? Which version of Techemistry? Which version of Forge? What exactly does it show when you try to login?

**Comment by TheRealM18** [comment]
This is on both client and server.

Minecraft-1.16.3
Forge-1.16.3-34.1.7
Techemistry 1.16.3-3

**Comment by ghost** [comment]
This should be fixed in 1.16.3-4 now, thank you.
