### ISSUE TITLE
[1.14.4] Maceration Station doesn't appear to consume power

### ISSUE THREAD

**Issue by noobanidus** [al132mc/techemistry#5]
Even when it's plugged in!

**Comment by noobanidus** [comment]
*not plugged in, rather.

**Comment by ghost** [comment]
There's nothing deeply broken here, apparently I set the energy consumption rate to 0 while I was testing something and forgot to set it back. I'll get a fix out shortly...

**Comment by ghost** [comment]
v15 is up which fixes this, thanks for reporting
