### ISSUE TITLE
[1.15.1] Steam Turbine generates infinite energy

### ISSUE THREAD

**Issue by SEbbaDK** [al132mc/techemistry#8]
I have the Steam Turbine hooked up to Mekaniks cables, and the turbine can be filled with steam and drained, but it won't go lower than 50 FE, at which point other machines still get energy, even if no water is in the boiler and no fuel is in the heater.

**Comment by ghost** [comment]
Fixed in 1.14.4-17 and 1.15.2-2, thank you for reporting.
